requires "Amazon::API::BuildInfo", "2.6.0";
requires "CLI::Simple", "2.2.1";
requires "CLI::Simple::Constants", "2.2.1";
requires "CLI::Simple::Utils", "2.2.1";
requires "File::ShareDir", "1.118";
requires "Pod::HTML2Pod", "4.05";
requires "Template", "3.102";
requires "Text::ASCIITable", "0.22";
suggests "IO::Pager", "2.10";
